"use client";

import { useEffect, useMemo, useState } from "react";

type Store={id:number;name:string;vertical:string;commissionRate:number};
type Slab={id?:number;storeId:number;minAmount:number;maxAmount:number|null;commission:number;commissionType:"FIXED"|"PERCENT";isActive?:number};
const money=(v:number)=>`₹${Number(v||0).toLocaleString("en-IN")}`;

export default function CommissionSlabsPage({mode="super-admin"}:{mode?:"owner"|"super-admin"}){
 const readOnly=mode!=="owner";
 const [stores,setStores]=useState<Store[]>([]),[storeId,setStoreId]=useState(0),[slabs,setSlabs]=useState<Slab[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const selectedStore=useMemo(()=>stores.find(s=>s.id===storeId)||null,[stores,storeId]);
 async function loadStores(){setLoading(true);setError("");try{const r=await fetch("/api/admin/control",{cache:"no-store"});if(r.status===401){window.location.href="/panel-login";return}const d=await r.json();if(!r.ok)throw new Error(d.error||"Panel load failed");const ns=(d.stores||[]) as Store[];setStores(ns);if(!storeId&&ns[0])setStoreId(ns[0].id)}catch(e){setError(e instanceof Error?e.message:"Panel load failed")}finally{setLoading(false)}}
 async function loadSlabs(id:number){if(!id){setSlabs([]);return}try{const r=await fetch(`/api/admin/commission-slabs?storeId=${id}`,{cache:"no-store"});if(r.status===401){window.location.href="/panel-login";return}const d=await r.json();if(!r.ok)throw new Error(d.error||"Slabs load nahi hue");setSlabs((d.slabs||[]).map((s:Slab)=>({...s,storeId:id})))}catch(e){setError(e instanceof Error?e.message:"Slabs load nahi hue")}}
 useEffect(()=>{void loadStores()},[]);useEffect(()=>{void loadSlabs(storeId)},[storeId]);
 function addSlab(){const p=slabs[slabs.length-1];setSlabs(c=>[...c,{storeId,minAmount:p?Number(p.maxAmount||p.minAmount+500):0,maxAmount:null,commission:selectedStore?.commissionRate||0,commissionType:"PERCENT",isActive:1}])}
 function updateSlab(i:number,p:Partial<Slab>){setSlabs(c=>c.map((s,n)=>n===i?{...s,...p}:s))} function removeSlab(i:number){setSlabs(c=>c.filter((_,n)=>n!==i))}
 async function save(){if(readOnly||!storeId)return;setSaving(true);setError("");setMessage("");try{const normalized=slabs.map(s=>({minAmount:Number(s.minAmount),maxAmount:s.maxAmount==null||s.maxAmount===""?null:Number(s.maxAmount),commission:Number(s.commission),commissionType:s.commissionType}));for(let i=0;i<normalized.length;i++){const s=normalized[i];if(!Number.isFinite(s.minAmount)||s.minAmount<0||!Number.isFinite(s.commission)||s.commission<0)throw new Error(`Slab ${i+1}: amount aur commission valid rakho`);if(s.maxAmount!==null&&(!Number.isFinite(s.maxAmount)||s.maxAmount<=s.minAmount))throw new Error(`Slab ${i+1}: Max amount, Min amount se bada hona chahiye`);if(i>0&&s.minAmount<normalized[i-1].minAmount)throw new Error("Slabs ko amount ke ascending order mein rakho")};const r=await fetch("/api/admin/commission-slabs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"replace",storeId,slabs:normalized})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save nahi hua");await loadSlabs(storeId);setMessage("Commission slabs saved successfully");setTimeout(()=>setMessage(""),2500)}catch(e){setError(e instanceof Error?e.message:"Save nahi hua")}finally{setSaving(false)}}
 return <main style={{minHeight:"100vh",background:"#f5f7fb",color:"#172033",padding:28,fontFamily:"Inter,system-ui,sans-serif"}}><div style={{maxWidth:1180,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",marginBottom:22}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.5,color:"#e53935"}}>SABKA DELIVERY · {readOnly?"SUPER ADMIN":"OWNER"}</div><h1 style={{margin:"6px 0 4px",fontSize:30}}>{readOnly?"Commission Slabs":"Commission Slab Editor"}</h1><p style={{margin:0,color:"#667085"}}>{readOnly?"Store-wise commission slabs — read only. Owner can edit these rules.":"Har shop ke order amount ke hisaab se commission directly set karo."}</p></div><a href={readOnly?"/super-admin":"/owner-panel"} style={{textDecoration:"none",border:"1px solid #d8dee9",background:"#fff",color:"#172033",padding:"11px 16px",borderRadius:10,fontWeight:700}}>← Control Room</a></header>
  {error&&<div style={{background:"#fff1f0",color:"#b42318",border:"1px solid #ffc7c2",padding:13,borderRadius:10,marginBottom:16}}>{error}</div>}{message&&<div style={{background:"#ecfdf3",color:"#067647",border:"1px solid #abefc6",padding:13,borderRadius:10,marginBottom:16}}>{message}</div>}
  <section style={{background:"#fff",border:"1px solid #e5e9f0",borderRadius:16,padding:20,marginBottom:18}}><label style={{display:"block",fontSize:12,fontWeight:800,color:"#667085",marginBottom:8}}>SELECT SHOP</label><select value={storeId||""} onChange={e=>setStoreId(Number(e.target.value))} disabled={loading} style={{width:"100%",maxWidth:520,padding:"13px 14px",borderRadius:10,border:"1px solid #cfd6e4",background:"#fff",fontSize:15}}><option value="">{loading?"Loading shops…":"Select a shop"}</option>{stores.map(s=><option value={s.id} key={s.id}>{s.name} · {s.vertical}</option>)}</select>{selectedStore&&<div style={{marginTop:10,fontSize:13,color:"#667085"}}>Current fallback commission: <b>{selectedStore.commissionRate}%</b></div>}</section>
  <section style={{background:"#fff",border:"1px solid #e5e9f0",borderRadius:16,overflow:"hidden"}}><div style={{padding:20,borderBottom:"1px solid #edf0f5",display:"flex",justifyContent:"space-between",alignItems:"center",gap:15}}><div><h2 style={{margin:0,fontSize:20}}>Order-value slabs</h2><p style={{margin:"5px 0 0",color:"#667085",fontSize:13}}>Example: ₹0–₹30 → ₹5 · ₹31–₹100 → ₹10 · ₹101–₹300 → ₹20 · ₹301+ → ₹30</p></div>{!readOnly&&<button onClick={addSlab} disabled={!storeId} style={{border:0,background:"#172033",color:"#fff",padding:"11px 16px",borderRadius:10,fontWeight:800}}>+ Add slab</button>}</div>
   <div style={{padding:20}}>{slabs.length===0?<div style={{padding:40,textAlign:"center",border:"1px dashed #cfd6e4",borderRadius:12,color:"#667085"}}><b style={{display:"block",color:"#172033",marginBottom:6}}>No slabs configured</b>{readOnly?"No commission slabs configured for this shop.":"Add your first slab."}</div>:<div style={{display:"grid",gap:12}}>{slabs.map((s,i)=><div key={s.id||`new-${i}`} style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 150px 46px",gap:10,alignItems:"end",padding:14,background:"#f8fafc",border:"1px solid #e5e9f0",borderRadius:12}}><Field label="Min order"><input disabled={readOnly} type="number" min="0" value={s.minAmount} onChange={e=>updateSlab(i,{minAmount:Number(e.target.value)})}/></Field><Field label="Max order (blank = no limit)"><input disabled={readOnly} type="number" min="0" value={s.maxAmount??""} onChange={e=>updateSlab(i,{maxAmount:e.target.value===""?null:Number(e.target.value)})} placeholder="No limit"/></Field><Field label="Commission"><input disabled={readOnly} type="number" min="0" step="0.01" value={s.commission} onChange={e=>updateSlab(i,{commission:Number(e.target.value)})}/></Field><Field label="Type"><select disabled={readOnly} value={s.commissionType} onChange={e=>updateSlab(i,{commissionType:e.target.value as Slab["commissionType"]})}><option value="PERCENT">Percent %</option><option value="FIXED">Fixed ₹</option></select></Field>{!readOnly&&<button onClick={()=>removeSlab(i)} title="Remove slab" style={{width:46,height:42,borderRadius:9,border:"1px solid #f0b7b2",background:"#fff5f4",color:"#b42318",fontWeight:900}}>×</button>}</div>)}</div>}
   {slabs.length>0&&<div style={{marginTop:16,padding:14,borderRadius:10,background:"#f5f7fb",color:"#667085",fontSize:13}}><b style={{color:"#172033"}}>Preview:</b> {slabs.map((s,i)=><span key={i}>{i?" · ":""}{money(s.minAmount)}{s.maxAmount!==null?`–${money(s.maxAmount)}`:"+"} → {s.commission}{s.commissionType==="PERCENT"?"%":" fixed"}</span>)}</div>}
   {!readOnly&&<div style={{marginTop:20,display:"flex",justifyContent:"flex-end",gap:10}}><button onClick={()=>void loadSlabs(storeId)} disabled={!storeId||saving} style={{border:"1px solid #d8dee9",background:"#fff",padding:"12px 18px",borderRadius:10,fontWeight:800}}>Reset</button><button onClick={()=>void save()} disabled={!storeId||saving} style={{border:0,background:"#e53935",color:"#fff",padding:"12px 22px",borderRadius:10,fontWeight:900,minWidth:150}}>{saving?"Saving…":"Save slabs"}</button></div>}
  </div></section></div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"grid",gap:6,fontSize:11,fontWeight:800,color:"#667085"}}>{label}<span>{children}</span><style jsx>{`input,select{box-sizing:border-box;width:100%;height:42px;padding:0 11px;border:1px solid #cfd6e4;border-radius:9px;background:#fff;color:#172033;font:inherit;font-size:14px;outline:none}input:disabled,select:disabled{background:#eef1f5;color:#475467;cursor:not-allowed}`}</style></label>}
