"use client";

import { useCallback, useMemo, useRef, useState, type FormEvent } from "react";
import ImagePicker from "../components/image-picker";
import FullItemEditor from "../components/full-item-editor";
import AdminWebsiteEditor, { type WebsiteContentBlock } from "../components/admin-website-editor";
import CouponManager, { type AdminCoupon } from "../components/coupon-manager";
import RewardOfferManager, { type AdminRewardOffer } from "../components/reward-offer-manager";
import ServiceAreaManager from "../components/service-area-manager";
import { requestBackgroundNotifications, showBackgroundNotification } from "../components/background-notifications";
import { useLiveRefresh } from "../components/use-live-refresh";
import { QRCodeSVG } from "qrcode.react";

type Store={id:number;name:string;vertical:string;description:string;address:string;image:string;isOpen:number;approved:number;blocked:number;commissionRate:number;openingTime:string;closingTime:string};
type Account={username:string;role:string;panelType:string;displayName:string;storeId:number|null;riderId:number|null;isActive:number;lastLogin:string|null};
type Rider={id:number;name:string;email:string;phone:string;isOnline:number;documentStatus:string;weeklyPayout:number;codCollection:number;upiId:string};
type Payout={id:number;riderId:number;riderName:string;riderPhone:string;amount:number;status:string;upiId:string;reference:string;createdAt:string;completedAt:string|null};
type Order={orderCode:string;customerName:string;mobile:string;address:string;area:string;paymentMethod:string;subtotal:number;deliveryFee:number;total:number;status:string;createdAt:string;storeName:string;storeId:number;riderId:number|null;riderName:string|null;paymentStatus:string|null};
type OrderItem={orderCode:string;itemName:string;variantLabel:string;quantity:number;unitPrice:number};
type Item={id:number;storeId:number;storeName:string;name:string;description:string;category:string;subcategory:string;foodType:string;image:string;isActive:number;variantId:number;label:string;unit:string;unitValue:number;price:number;discountPrice:number;discountPercent:number;stockQuantity:number};
type Category={id:number;name:string;image:string;isActive:number;sortOrder:number;vertical:string;derived?:boolean};
type MarketSection={key:string;name:string;description:string;image:string;icon:string;isActive:number;sortOrder:number;minOrder:number;deliveryCharge:number};
type Notice={id:number;type:string;title:string;message:string;orderCode:string|null;isRead:number;createdAt:string};
type Data={owner:string;stores:Store[];accounts:Account[];riders:Rider[];payouts:Payout[];orders:Order[];orderItems:OrderItem[];items:Item[];categories:Category[];sections:MarketSection[];notifications:Notice[];settings:Record<string,string>;promotions:AdminCoupon[];offers:AdminRewardOffer[];content:WebsiteContentBlock[];summary:{totalOrders:number;totalSales:number;activeOrders:number;openStores:number;onlineRiders:number;activePanels:number}};
type Tab="Dashboard"|"Orders"|"Shops"|"Catalog"|"Sections"|"Categories"|"Delivery Areas"|"Offers"|"Coupons"|"Website Editor"|"Panel Users"|"Riders"|"Withdrawals"|"Settings";
const statuses=["ACCEPTED","CONFIRMED","PREPARING","PACKING","READY_FOR_PICKUP","OUT_FOR_DELIVERY","DELIVERED","CANCELLED"];
const money=(value:number)=>`₹${Number(value||0).toLocaleString("en-IN")}`;

export default function AdminConsole({owner}:{owner:string}){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState<Tab>("Dashboard"),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false),[alerts,setAlerts]=useState(false);
 const knownOrders=useRef<Set<string>|null>(null);
 const payloadSignature=useRef("");
 const mutating=useRef(false);
 const loading=useRef(false);
 const beep=useCallback(()=>{try{const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;const context=new AudioContextClass();const oscillator=context.createOscillator();const gain=context.createGain();oscillator.frequency.value=880;gain.gain.value=.08;oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.22);}catch{}},[]);
 const load=useCallback(async()=>{if(mutating.current||loading.current)return;loading.current=true;const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),15000);try{const response=await fetch("/api/admin/control",{cache:"no-store",signal:controller.signal});if(response.status===401){location.href="/panel-login";return}const result=await response.json();if(!response.ok){setError(result.error||"Panel load failed");return}const signature=JSON.stringify(result);if(signature===payloadSignature.current)return;payloadSignature.current=signature;const incoming=(result.orders as Order[]).filter(order=>!knownOrders.current?.has(order.orderCode)&&order.status==="ACCEPTED");if(knownOrders.current&&incoming.length&&alerts){beep();void showBackgroundNotification({title:"SABKA DELIVERY · New order",body:`${incoming[0].storeName} · ${money(incoming[0].total)} · ${incoming[0].orderCode}`,url:"/super-admin",tag:`admin-order-${incoming[0].orderCode}`});}knownOrders.current=new Set((result.orders as Order[]).map(order=>order.orderCode));setData(result);setError("");}catch(error){if((error as Error).name!=="AbortError")setError("Admin data load nahi hua—Retry dabao");}finally{window.clearTimeout(timeout);loading.current=false}},[alerts,beep]);
 useLiveRefresh(load,5000,{runWhenHidden:alerts});
 async function send(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>){if(mutating.current)return false;mutating.current=true;setBusy(true);setError("");setSuccess("");const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),20000);let saved=false;try{const response=await fetch("/api/admin/control",{method,headers:{"Content-Type":"application/json","Cache-Control":"no-store"},body:JSON.stringify(body),signal:controller.signal});const result=await response.json().catch(()=>({error:"Server response invalid hai"}));if(response.status===401){location.href="/panel-login";return false}if(!response.ok){setError(result.error||"Action failed");return false}saved=true;payloadSignature.current="";setSuccess(method==="DELETE"?"Delete successful":"Changes saved successfully");window.setTimeout(()=>setSuccess(""),2500);return true}catch(error){setError((error as Error).name==="AbortError"?"Request timeout—dobara try karo":"Network problem—dobara try karo");return false}finally{window.clearTimeout(timeout);mutating.current=false;setBusy(false);if(saved)window.setTimeout(()=>void load(),0)}}
 async function enableAlerts(){const enabled=await requestBackgroundNotifications("SABKA DELIVERY alerts enabled","New order aate hi background notification milega.","/super-admin");if(enabled){setAlerts(true);beep();}else setError("Notification permission allow karo");}
 const unread=data?.notifications.filter(n=>!n.isRead).length||0;
 if(!data)return <main className="panel-loading"><img src="/images/sabka-delivery-logo.png" alt=""/><h1>Control room load ho raha hai…</h1><p>{error}</p></main>;
 return <main className="admin-app">
  <aside className="admin-side"><a className="admin-logo" href="/super-admin"><img src="/images/sabka-delivery-logo.png" alt=""/><span>SABKA<b>CONTROL ROOM</b></span></a><nav>{(["Dashboard","Orders","Shops","Catalog","Sections","Categories","Offers","Coupons","Website Editor","Panel Users","Riders","Withdrawals","Settings"] as Tab[]).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}><i>{item==="Dashboard"?"⌂":item==="Orders"?"▣":item==="Shops"?"⌂":item==="Catalog"?"≡":item==="Sections"?"◫":item==="Categories"?"▦":item==="Offers"?"★":item==="Coupons"?"%":item==="Website Editor"?"✎":item==="Panel Users"?"●":item==="Riders"?"➜":item==="Withdrawals"?"₹":"⚙"}</i>{item}{item==="Orders"&&data.summary.activeOrders>0?<em>{data.summary.activeOrders}</em>:null}{item==="Withdrawals"&&data.payouts.some(p=>p.status==="PENDING")?<em>{data.payouts.filter(p=>p.status==="PENDING").length}</em>:null}</button>)}</nav><div className="admin-user"><span>{owner.slice(0,1)}</span><p><b>{owner}</b><small>Super Admin</small></p><a href="/api/panel-auth/logout">Sign out</a></div></aside>
  <section className="admin-work"><header className="admin-top"><div><small>SABKA DELIVERY · LALA BAZAR</small><h1>{tab}</h1></div><div><button className={alerts?"alert-on":""} onClick={enableAlerts}>🔔 {alerts?"Alerts on":"Enable alerts"}</button><button onClick={()=>void load()}>↻ Retry</button><a href="/" target="_blank">Customer site ↗</a></div></header>{error&&<div className="panel-error">{error}<button onClick={()=>setError("")}>×</button></div>}{success&&<div className="panel-success">✓ {success}</div>}
   {tab==="Dashboard"&&<Dashboard data={data} unread={unread} onRead={id=>send("PATCH",{action:"notificationRead",id})}/>} 
   {tab==="Orders"&&<Orders data={data} send={send}/>} 
   {tab==="Shops"&&<ShopsV2 data={data} send={send} busy={busy}/>} 
   {tab==="Catalog"&&<Catalog data={data} send={send} busy={busy}/>} 
   {tab==="Sections"&&<SectionManager data={data} send={send} busy={busy}/>}
   {tab==="Categories"&&<CategoryManager data={data} send={send} busy={busy}/>}
   {tab==="Offers"&&<RewardOfferManager offers={data.offers} send={send} busy={busy}/>}
   {tab==="Coupons"&&<CouponManager coupons={data.promotions} send={send} busy={busy}/>}
   {tab==="Website Editor"&&<AdminWebsiteEditor content={data.content} settings={data.settings} send={send} busy={busy}/>}
   {tab==="Panel Users"&&<PanelUsers data={data} send={send} busy={busy}/>} 
   {tab==="Riders"&&<Riders data={data} send={send} busy={busy}/>} 
   {tab==="Withdrawals"&&<Withdrawals payouts={data.payouts} send={send} busy={busy}/>}
   {tab==="Settings"&&<Settings data={data} send={send} busy={busy}/>} 
  </section>
 </main>
}

function Dashboard({data,unread,onRead}:{data:Data;unread:number;onRead:(id:number)=>void}){const metrics=[{label:"Today's sales",value:money(data.summary.totalSales),tone:"red"},{label:"Today's orders",value:data.summary.totalOrders,tone:"green"},{label:"Today's active orders",value:data.summary.activeOrders,tone:"orange"},{label:"Open shops",value:data.summary.openStores,tone:"blue"},{label:"Online riders",value:data.summary.onlineRiders,tone:"purple"},{label:"Active panels",value:data.summary.activePanels,tone:"dark"}];return <><p className="daily-reset-note">Daily counters automatically reset at 12:00 AM IST. Order history safe rahegi.</p><section className="metric-grid">{metrics.map(metric=><article className={metric.tone} key={metric.label}><small>{metric.label}</small><strong>{metric.value}</strong><span>Live database · resets midnight</span></article>)}</section><section className="dashboard-grid"><article className="live-orders"><div className="section-head"><div><small>LIVE QUEUE</small><h2>Active orders</h2></div><b>{data.summary.activeOrders}</b></div>{data.orders.filter(o=>!["DELIVERED","CANCELLED"].includes(o.status)).slice(0,8).map(order=><div className="order-row" key={order.orderCode}><span className={`status ${order.status.toLowerCase()}`}>{order.status.replaceAll("_"," ")}</span><p><b>{order.storeName}</b><small>{order.orderCode} · {order.customerName}</small></p><strong>{money(order.total)}</strong></div>)}{!data.orders.some(o=>!["DELIVERED","CANCELLED"].includes(o.status))&&<Empty text="Abhi koi active order nahi hai"/>}</article><article className="notification-feed"><div className="section-head"><div><small>NOTIFICATIONS</small><h2>Order alerts</h2></div><b>{unread}</b></div>{data.notifications.slice(0,10).map(notice=><button className={notice.isRead?"":"unread"} key={notice.id} onClick={()=>onRead(notice.id)}><i>{notice.type==="PAYMENT"?"₹":"●"}</i><span><b>{notice.title}</b><small>{notice.message}</small></span><time>{new Date(notice.createdAt+"Z").toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}</time></button>)}{!data.notifications.length&&<Empty text="New order aate hi alert yahan dikhega"/>}</article></section></>}

function Orders({data,send}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>}){return <section className="order-board">{data.orders.map(order=>{const lines=data.orderItems.filter(line=>line.orderCode===order.orderCode);return <article className="order-card" key={order.orderCode}><header><div><span className={`status ${order.status.toLowerCase()}`}>{order.status.replaceAll("_"," ")}</span><h2>{order.orderCode}</h2><small>{new Date(order.createdAt+"Z").toLocaleString("en-IN")}</small></div><strong>{money(order.total)}</strong></header><div className="order-columns"><p><small>CUSTOMER</small><b>{order.customerName}</b><a href={`tel:${order.mobile}`}>{order.mobile}</a><span>{order.address}, {order.area}</span></p><p><small>SHOP</small><b>{order.storeName}</b><span>{lines.map(line=>`${line.quantity}× ${line.itemName}`).join(", ")||"Items"}</span></p><p><small>PAYMENT</small><b>{order.paymentMethod} · {order.paymentStatus||"PENDING"}</b><span>Delivery {money(order.deliveryFee)}</span></p></div><footer><select value={order.status} onChange={event=>send("PATCH",{action:"order",orderCode:order.orderCode,status:event.target.value})}>{statuses.map(status=><option key={status}>{status}</option>)}</select><select value={order.riderId||""} onChange={event=>event.target.value&&send("PATCH",{action:"assignRider",orderCode:order.orderCode,riderId:Number(event.target.value)})}><option value="">Assign rider</option>{data.riders.map(rider=><option value={rider.id} key={rider.id}>{rider.name}</option>)}</select>{order.paymentMethod==="UPI"&&order.paymentStatus!=="VERIFIED"?<button onClick={()=>send("PATCH",{action:"payment",orderCode:order.orderCode,status:"VERIFIED"})}>Verify UPI</button>:null}</footer></article>})}{!data.orders.length&&<Empty text="Orders abhi zero hain"/>}</section>}

function Shops({data,send,busy}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){const [image,setImage]=useState("");function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const form=new FormData(target);void send("POST",{action:"shop",name:form.get("name"),vertical:form.get("vertical"),address:form.get("address"),description:form.get("description"),openingTime:form.get("openingTime"),closingTime:form.get("closingTime"),image}).then(ok=>{if(ok){target.reset();setImage("")}})}return <><form className="create-strip shop-create" onSubmit={submit}><div><small>NEW BUSINESS</small><h2>Add shop</h2></div><input name="name" required placeholder="Shop / restaurant name"/><select name="vertical" required>{data.sections.filter(section=>section.isActive).map(section=><option value={section.key} key={section.key}>{section.icon} {section.name}</option>)}</select><input name="address" required placeholder="Address"/><input name="description" placeholder="Short description"/><label className="shop-hours">Opens<input name="openingTime" type="time" required defaultValue="09:00"/></label><label className="shop-hours">Closes<input name="closingTime" type="time" required defaultValue="22:00"/></label><ImagePicker value={image} onChange={setImage} label="Select shop photo"/><button disabled={busy}>Add shop</button></form><p className="category-help"><b>Warning:</b> Shop delete karne par us shop ke items, panel users aur saare old/current orders permanently delete honge.</p><section className="shop-grid">{data.stores.map(store=><article key={store.id}><img src={store.image||"/images/hero-food-collage.png"} alt=""/><div><span>{store.vertical}</span><h2>{store.name}</h2><p>{store.address}</p><small>{store.commissionRate||18}% commission · {store.openingTime||"09:00"}–{store.closingTime||"22:00"}</small></div><footer><button className={store.isOpen?"online":"offline"} onClick={()=>send("PATCH",{action:"shop",storeId:store.id,isOpen:!store.isOpen})}>{store.isOpen?"● Accepting orders":"○ Offline"}</button><button className="danger" onClick={()=>confirm(`${store.name} aur is shop ke SAARE ORDERS permanently delete karein? Yeh undo nahi hoga.`)&&send("DELETE",{action:"shop",storeId:store.id})}>Delete shop + orders</button></footer></article>)}{!data.stores.length&&<Empty text="Pehla shop add karo"/>}</section></>}

function ShopsV2({data,send,busy}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [image,setImage]=useState("");
 const activeSections=data.sections.filter(section=>section.isActive);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const form=new FormData(target);void send("POST",{action:"shop",name:form.get("name"),vertical:form.get("vertical"),address:form.get("address"),description:form.get("description"),openingTime:form.get("openingTime"),closingTime:form.get("closingTime"),image}).then(ok=>{if(ok){target.reset();setImage("")}})}
 return <>
  <form className="create-strip shop-create" onSubmit={submit}>
   <div><small>NEW BUSINESS</small><h2>Add shop</h2></div>
   <input name="name" required placeholder="Shop / restaurant name"/>
   <select name="vertical" required>{activeSections.map(section=><option value={section.key} key={section.key}>{section.icon} {section.name}</option>)}</select>
   <input name="address" required placeholder="Address"/>
   <input name="description" placeholder="Short description"/>
   <label className="shop-hours">Opens<input name="openingTime" type="time" required defaultValue="09:00"/></label>
   <label className="shop-hours">Closes<input name="closingTime" type="time" required defaultValue="22:00"/></label>
   <ImagePicker value={image} onChange={setImage} label="Select shop photo"/>
   <button disabled={busy||!activeSections.length}>Add shop</button>
  </form>
  <p className="category-help"><b>Warning:</b> Shop delete karne par us shop ke items, panel users aur saare old/current orders permanently delete honge.</p>
  <section className="shop-grid">
   {data.stores.map(store=><ShopCard key={store.id} store={store} sections={activeSections} send={send} busy={busy}/>)}
   {!data.stores.length&&<Empty text="Pehla shop add karo"/>}
  </section>
 </>;
}

function ShopCard({store,sections,send,busy}:{store:Store;sections:MarketSection[];send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [editing,setEditing]=useState(false),[name,setName]=useState(store.name),[vertical,setVertical]=useState(store.vertical||"FOOD"),[address,setAddress]=useState(store.address||""),[description,setDescription]=useState(store.description||""),[openingTime,setOpeningTime]=useState(store.openingTime||"09:00"),[closingTime,setClosingTime]=useState(store.closingTime||"22:00"),[image,setImage]=useState(store.image||""),[isOpen,setIsOpen]=useState(!!store.isOpen),[saved,setSaved]=useState(false);
 const sectionOptions=sections.some(section=>section.key===vertical)?sections:[{key:vertical,name:vertical,description:"",image:"",icon:"",isActive:1,sortOrder:0,minOrder:0,deliveryCharge:0},...sections];
 function reset(){setName(store.name);setVertical(store.vertical||"FOOD");setAddress(store.address||"");setDescription(store.description||"");setOpeningTime(store.openingTime||"09:00");setClosingTime(store.closingTime||"22:00");setImage(store.image||"");setIsOpen(!!store.isOpen);setEditing(false)}
 async function toggleOpen(){const next=!isOpen;const ok=await send("PATCH",{action:"shop",storeId:store.id,isOpen:next});if(ok)setIsOpen(next)}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaved(false);const ok=await send("PATCH",{action:"shop",storeId:store.id,name,vertical,address,description,openingTime,closingTime,image,isOpen});if(ok){setEditing(false);setSaved(true);window.setTimeout(()=>setSaved(false),2200)}}
 if(editing)return <article className="shop-editing-card"><form className="shop-card-edit" onSubmit={save}>
  <ImagePicker value={image} onChange={setImage} label="Select shop photo"/>
  <label>Name<input value={name} onChange={event=>setName(event.target.value)} required/></label>
  <label>Section<select value={vertical} onChange={event=>setVertical(event.target.value)} required>{sectionOptions.map(section=><option value={section.key} key={section.key}>{section.icon} {section.name}</option>)}</select></label>
  <label>Address<input value={address} onChange={event=>setAddress(event.target.value)} required/></label>
  <label>Description<textarea rows={3} value={description} onChange={event=>setDescription(event.target.value)}/></label>
  <div className="shop-time-fields"><label>Opens<input type="time" value={openingTime} onChange={event=>setOpeningTime(event.target.value)} required/></label><label>Closes<input type="time" value={closingTime} onChange={event=>setClosingTime(event.target.value)} required/></label></div>
  <label className="shop-edit-status"><input type="checkbox" checked={isOpen} onChange={event=>setIsOpen(event.target.checked)}/><span>Accepting orders</span></label>
  <footer className="shop-edit-actions"><button type="submit" disabled={busy}>Save shop</button><button type="button" onClick={reset} disabled={busy}>Cancel</button><button type="button" className="danger" disabled={busy} onClick={()=>confirm(`${store.name} aur is shop ke SAARE ORDERS permanently delete karein? Yeh undo nahi hoga.`)&&send("DELETE",{action:"shop",storeId:store.id})}>Delete</button></footer>
 </form></article>;
 return <article><img src={image||"/images/hero-food-collage.png"} alt=""/><div><span>{vertical}</span><h2>{name}</h2><p>{address}</p><small>{store.commissionRate||18}% commission - {openingTime} to {closingTime}</small>{saved&&<em className="shop-saved">Saved</em>}</div><footer><button className={isOpen?"online":"offline"} onClick={toggleOpen} disabled={busy}>{isOpen?"Accepting orders":"Offline"}</button><button onClick={()=>setEditing(true)} disabled={busy}>Edit</button><button className="danger" onClick={()=>confirm(`${store.name} aur is shop ke SAARE ORDERS permanently delete karein? Yeh undo nahi hoga.`)&&send("DELETE",{action:"shop",storeId:store.id})} disabled={busy}>Delete</button></footer></article>;
}

function Catalog({data,send,busy}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [image,setImage]=useState("");
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const form=new FormData(target);void send("POST",{action:"item",storeId:Number(form.get("storeId")),name:form.get("name"),category:form.get("category"),foodType:form.get("foodType"),label:form.get("label"),unit:form.get("unit"),price:Number(form.get("price")),discountPrice:Number(form.get("discountPrice")||form.get("price")||0),stockQuantity:Number(form.get("stock")),image}).then(ok=>{if(ok){target.reset();setImage("")}})}
 return <>
  <form className="create-strip catalog-create" onSubmit={submit}><div><small>CATALOG</small><h2>Add item</h2></div><select name="storeId" required><option value="">Select shop</option>{data.stores.map(store=><option value={store.id} key={store.id}>{store.name}</option>)}</select><input name="name" required placeholder="Item name"/><input name="category" required placeholder="Category"/><select name="foodType"><option>VEG</option><option>NON_VEG</option><option>EGG</option></select><input name="label" required placeholder="500 g / Full plate"/><select name="unit"><option>PIECE</option><option>PACK</option><option>PLATE</option><option>GM</option><option>KG</option><option>ML</option><option>LITRE</option></select><input name="price" type="number" min="0" required placeholder="Regular price"/><input name="discountPrice" type="number" min="0" required placeholder="Offer price"/><input name="stock" type="number" min="0" required placeholder="Stock"/><ImagePicker value={image} onChange={setImage} label="Select item photo"/><button disabled={busy||!data.stores.length}>Add item</button></form>
  <section className="catalog-table">{data.items.map(item=><article key={item.variantId}><img src={item.image||"/images/hero-food.png"} alt=""/><p><b>{item.name}</b><small>{item.storeName} · {item.category} · {item.label}</small></p><label>Price<input id={`p-${item.variantId}`} type="number" min="0" defaultValue={item.price}/></label><label>Offer price<input id={`op-${item.variantId}`} type="number" min="0" defaultValue={item.discountPrice||item.price}/></label><label>Discount %<input value={item.discountPercent||0} readOnly/></label><label>Stock<input id={`s-${item.variantId}`} type="number" min="0" defaultValue={item.stockQuantity}/></label><label className="stock-check"><input id={`a-${item.variantId}`} type="checkbox" defaultChecked={!!item.isActive}/>Live</label><button onClick={()=>send("PATCH",{action:"item",variantId:item.variantId,price:Number((document.getElementById(`p-${item.variantId}`) as HTMLInputElement).value),discountPrice:Number((document.getElementById(`op-${item.variantId}`) as HTMLInputElement).value),stockQuantity:Number((document.getElementById(`s-${item.variantId}`) as HTMLInputElement).value),isActive:(document.getElementById(`a-${item.variantId}`) as HTMLInputElement).checked})}>Quick save</button><FullItemEditor item={item} stores={data.stores} onSave={values=>send("PATCH",{action:"item",...values})}/><button className="danger" onClick={()=>confirm(`${item.name} delete karein?`)&&send("DELETE",{action:"item",itemId:item.id})}>Delete</button></article>)}{!data.items.length&&<Empty text="Catalog abhi khaali hai"/>}</section>
 </>
}

function SectionManager({data,send,busy}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [image,setImage]=useState("");
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const form=new FormData(target);void send("POST",{action:"section",name:form.get("name"),description:form.get("description"),icon:form.get("icon"),sortOrder:Number(form.get("sortOrder")||0),image}).then(ok=>{if(ok){target.reset();setImage("")}})}
 return <>
  <form className="create-strip section-create" onSubmit={submit}><div><small>TOP-LEVEL CUSTOMER MENU</small><h2>Add section</h2></div><input name="name" required placeholder="Section name, e.g. Electronics"/><input name="icon" maxLength={4} defaultValue="▦" placeholder="Icon"/><input name="description" placeholder="Short section description"/><input name="sortOrder" type="number" min="0" max="999" defaultValue="10" placeholder="Display order"/><ImagePicker value={image} onChange={setImage} label="Select section image"/><button disabled={busy}>Add section</button></form>
  <p className="category-help">Yahan se Food, Grocery, Electronics ya koi bhi naya top-level section add, rename, reorder aur show/hide kar sakte ho. Shop add karte waqt section select hoga.</p>
  <section className="category-admin-grid">{data.sections.map(section=><SectionCard key={section.key} section={section} send={send} busy={busy}/>)}</section>
 </>;
}

function SectionCard({section,send,busy}:{section:MarketSection;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [name,setName]=useState(section.name),[description,setDescription]=useState(section.description),[image,setImage]=useState(section.image),[icon,setIcon]=useState(section.icon),[sortOrder,setSortOrder]=useState(section.sortOrder),[minOrder,setMinOrder]=useState(section.minOrder||0),[deliveryCharge,setDeliveryCharge]=useState(section.deliveryCharge??20),[isActive,setIsActive]=useState(!!section.isActive);
 const [saved,setSaved]=useState(false);
 const locked=["FOOD","GROCERY","ELECTRONICS"].includes(section.key);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaved(false);const ok=await send("PATCH",{action:"section",key:section.key,name,description,image,icon,sortOrder,minOrder,deliveryCharge,isActive});if(ok){setSaved(true);window.setTimeout(()=>setSaved(false),2500)}}
 return <form className="category-admin-card section-admin-card" onSubmit={save}><div className="category-card-head"><span>{icon} {section.key}</span><small>{locked?"Default section":"Custom section"}</small></div><ImagePicker value={image} onChange={setImage} label="Select section image"/><label>Name<input value={name} onChange={event=>setName(event.target.value)} required/></label><label>Description<textarea rows={3} value={description} onChange={event=>setDescription(event.target.value)}/></label><div className="category-card-fields"><label>Icon<input value={icon} maxLength={4} onChange={event=>setIcon(event.target.value)}/></label><label>Order<input type="number" min="0" max="999" value={sortOrder} onChange={event=>setSortOrder(Number(event.target.value))}/></label></div><label>Minimum order (₹)<input type="number" min="0" step="1" value={minOrder} onChange={event=>setMinOrder(Math.max(0,Number(event.target.value)))}/><small>₹0 rakhne par is section mein koi minimum order nahi hoga.</small></label><label>Delivery charge (₹)<input type="number" min="0" step="1" value={deliveryCharge} onChange={event=>setDeliveryCharge(Math.max(0,Number(event.target.value)))}/><small>Checkout mein is section ka delivery charge live use hoga.</small></label><label className="category-live"><input type="checkbox" checked={isActive} onChange={event=>setIsActive(event.target.checked)}/><span>Customer panel par show karo</span></label><footer><button type="submit" disabled={busy}>{busy?"Saving…":saved?"✓ Saved":"Save section"}</button>{!locked?<button type="button" className="danger" onClick={()=>confirm(`${section.name} section delete karein?`)&&send("DELETE",{action:"section",key:section.key})}>Delete</button>:null}</footer></form>;
}

function CategoryManager({data,send,busy}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [image,setImage]=useState("");
 const categories=useMemo(()=>{
  const merged=new Map<string,Category>();
  for(const vertical of data.sections.map(section=>section.key)){
   merged.set(`${vertical}:all`,{id:0,name:"All",image:"",isActive:1,sortOrder:0,vertical,derived:true});
  }
  for(const item of data.items){
   const store=data.stores.find(entry=>entry.id===item.storeId);
   const vertical=store?.vertical||"FOOD";
   const key=`${vertical}:${item.category.trim().toLowerCase()}`;
   if(!merged.has(key))merged.set(key,{id:0,name:item.category,image:"",isActive:1,sortOrder:99,vertical,derived:true});
  }
  for(const category of data.categories)merged.set(`${category.vertical}:${category.name.trim().toLowerCase()}`,category);
  return [...merged.values()].sort((left,right)=>left.vertical.localeCompare(right.vertical)||left.sortOrder-right.sortOrder||left.name.localeCompare(right.name));
 },[data.categories,data.items,data.sections,data.stores]);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const form=new FormData(target);void send("POST",{action:"category",name:form.get("name"),vertical:form.get("vertical"),sortOrder:Number(form.get("sortOrder")||0),image}).then(ok=>{if(ok){target.reset();setImage("")}})}
 return <>
  <form className="create-strip category-create" onSubmit={submit}>
   <div><small>CUSTOMER NAVIGATION</small><h2>Add category</h2></div>
   <input name="name" required placeholder="Category name, e.g. Drinks"/>
   <select name="vertical" defaultValue="GROCERY">{data.sections.map(section=><option value={section.key} key={section.key}>{section.icon} {section.name}</option>)}</select>
   <input name="sortOrder" type="number" min="0" max="999" defaultValue="10" placeholder="Order"/>
   <ImagePicker value={image} onChange={setImage} label="Select category photo"/>
   <button disabled={busy}>Save category</button>
  </form>
  <p className="category-help"><b>All</b> category ka photo bhi yahin edit hoga. Photo par tap karke gallery image select karo, phir <b>Save changes</b>. Existing item categories automatically dikhengi.</p>
  <section className="category-admin-grid">{categories.map(category=><CategoryCard key={category.id||`${category.vertical}:${category.name}`} category={category} sections={data.sections} send={send} busy={busy}/>)}</section>
 </>;
}

function CategoryCard({category,sections,send,busy}:{category:Category;sections:MarketSection[];send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [name,setName]=useState(category.name),[vertical,setVertical]=useState(category.vertical),[image,setImage]=useState(category.image),[sortOrder,setSortOrder]=useState(category.sortOrder),[isActive,setIsActive]=useState(!!category.isActive);
 const isAll=category.name.trim().toLowerCase()==="all";
 function save(event:FormEvent<HTMLFormElement>){event.preventDefault();void send(category.id?"PATCH":"POST",{action:"category",...(category.id?{id:category.id}:{}),name,vertical,image,sortOrder,isActive})}
 return <form className="category-admin-card" onSubmit={save}>
  <div className="category-card-head"><span>{vertical}</span>{category.derived?<small>{isAll?"All button · custom photo set nahi hai":"Item se detected · photo set nahi hai"}</small>:<small>Saved category</small>}</div>
  <ImagePicker value={image} onChange={setImage} label="Select thumbnail"/>
  <label>Name<input value={name} onChange={event=>setName(event.target.value)} required disabled={isAll}/></label>
  <div className="category-card-fields"><label>Section<select value={vertical} onChange={event=>setVertical(event.target.value)} disabled={isAll}>{sections.map(section=><option value={section.key} key={section.key}>{section.icon} {section.name}</option>)}</select></label><label>Order<input type="number" min="0" max="999" value={sortOrder} onChange={event=>setSortOrder(Number(event.target.value))}/></label></div>
  <label className="category-live"><input type="checkbox" checked={isActive} onChange={event=>setIsActive(event.target.checked)}/><span>Customer website par show karo</span></label>
  <footer><button disabled={busy}>Save changes</button>{category.id?<button type="button" className="danger" onClick={()=>confirm(isAll?`${category.vertical} All photo reset karein?`:`${category.name} category setting delete karein?`)&&send("DELETE",{action:"category",id:category.id})}>{isAll?"Reset photo":"Delete"}</button>:null}</footer>
 </form>;
}

function PanelUsers({data,send,busy}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [type,setType]=useState("RESTAURANT");
 const storesFor=(panelType:string)=>data.stores.filter(store=>store.vertical===(panelType==="RESTAURANT"?"FOOD":panelType));
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const form=new FormData(target);const storeId=Number(form.get("storeId")||0)||null,riderId=Number(form.get("riderId")||0)||null;void send("POST",{action:"account",username:form.get("username"),password:form.get("password"),displayName:form.get("displayName"),panelType:type,storeId,riderId}).then(ok=>ok&&target.reset())}
 function updateAccount(account:Account,values:Record<string,unknown>){const panelType=String(values.panelType||account.panelType),storeId=panelType==="DELIVERY"?null:Object.prototype.hasOwnProperty.call(values,"storeId")?Number(values.storeId)||null:account.storeId,riderId=panelType==="DELIVERY"?(Object.prototype.hasOwnProperty.call(values,"riderId")?Number(values.riderId)||null:account.riderId):null;void send("PATCH",{action:"account",username:account.username,panelType,storeId,riderId,isActive:Object.prototype.hasOwnProperty.call(values,"isActive")?values.isActive:!!account.isActive})}
 return <><form className="create-strip user-create" onSubmit={submit}><div><small>PRIVATE ACCESS</small><h2>Create panel user</h2></div><select value={type} onChange={event=>setType(event.target.value)}><option value="RESTAURANT">Restaurant panel</option><option value="GROCERY">Grocery panel</option><option value="ELECTRONICS">Electronics panel</option><option value="DELIVERY">Rider panel</option></select><input name="displayName" required placeholder="Display name"/><input name="username" required placeholder="User ID"/><input name="password" type="password" minLength={8} required placeholder="Password (8+ chars)"/>{type==="DELIVERY"?<select name="riderId"><option value="">Assign rider later</option>{data.riders.map(rider=><option value={rider.id} key={rider.id}>{rider.name}</option>)}</select>:<select name="storeId"><option value="">Assign shop later</option>{storesFor(type).map(store=><option value={store.id} key={store.id}>{store.name}</option>)}</select>}<button disabled={busy}>Create ID</button></form><section className="account-grid">{data.accounts.map(account=>{const owner=account.role==="SUPER_ADMIN",delivery=account.panelType==="DELIVERY";return <article key={account.username}><i>{account.displayName.slice(0,1)}</i><p><b>{account.displayName}</b><small>@{account.username}</small></p>{owner?<span>SUPER ADMIN</span>:<select value={account.panelType} onChange={event=>updateAccount(account,{panelType:event.target.value,storeId:null,riderId:null})}><option value="RESTAURANT">Restaurant panel</option><option value="GROCERY">Grocery panel</option><option value="ELECTRONICS">Electronics panel</option><option value="DELIVERY">Rider panel</option></select>}{!owner&&(delivery?<select value={account.riderId||""} onChange={event=>updateAccount(account,{riderId:event.target.value})}><option value="">Assign rider later</option>{data.riders.map(rider=><option value={rider.id} key={rider.id}>{rider.name}</option>)}</select>:<select value={account.storeId||""} onChange={event=>updateAccount(account,{storeId:event.target.value})}><option value="">Assign shop later</option>{storesFor(account.panelType).map(store=><option value={store.id} key={store.id}>{store.name}</option>)}</select>)}<time>{account.lastLogin?`Last login ${new Date(account.lastLogin+"Z").toLocaleDateString("en-IN")}`:"Never logged in"}</time>{owner?<strong>OWNER</strong>:<><button onClick={()=>updateAccount(account,{isActive:!account.isActive})}>{account.isActive?"Pause":"Enable"}</button><button className="danger" onClick={()=>confirm(`${account.username} delete karein?`)&&send("DELETE",{action:"account",username:account.username})}>Delete</button></>}</article>})}</section></>
}

function Riders({data,send,busy}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const form=new FormData(target);void send("POST",{action:"rider",name:form.get("name"),phone:form.get("phone"),email:form.get("email")}).then(ok=>ok&&target.reset())}return <><form className="create-strip" onSubmit={submit}><div><small>DELIVERY FLEET</small><h2>Add rider</h2></div><input name="name" required placeholder="Rider name"/><input name="phone" required pattern="[0-9]{10}" placeholder="10-digit phone"/><input name="email" type="email" placeholder="Email (optional)"/><button disabled={busy}>Add rider</button></form><section className="rider-grid">{data.riders.map(rider=><article key={rider.id}><span className={rider.isOnline?"online":"offline"}>{rider.isOnline?"ONLINE":"OFFLINE"}</span><i>{rider.name.slice(0,1)}</i><h2>{rider.name}</h2><a href={`tel:${rider.phone}`}>{rider.phone}</a><div><p><small>WEEKLY</small><b>{money(rider.weeklyPayout)}</b></p><p><small>COD HELD</small><b>{money(rider.codCollection)}</b></p></div><small>{rider.documentStatus} DOCUMENTS</small></article>)}{!data.riders.length&&<Empty text="Pehla rider add karo, phir uska panel ID banao"/>}</section></>}

function Withdrawals({payouts,send,busy}:{payouts:Payout[];send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){const [paying,setPaying]=useState<Payout|null>(null);const upiIntent=paying?`upi://pay?pa=${encodeURIComponent(paying.upiId)}&pn=${encodeURIComponent(paying.riderName)}&am=${Number(paying.amount).toFixed(2)}&cu=INR&tn=${encodeURIComponent(`SABKA rider withdrawal ${paying.id}`)}`:"";async function approve(payout:Payout){await send("PATCH",{action:"payout",payoutId:payout.id,payoutAction:"APPROVE"})}async function complete(){if(!paying)return;const ok=await send("PATCH",{action:"payout",payoutId:paying.id,payoutAction:"PAID",reference:`UPI PAID ${new Date().toISOString()}`});if(ok)setPaying(null)}return <><section className="withdrawal-board">{payouts.map(payout=><article key={payout.id}><header><span className={payout.status.toLowerCase()}>{payout.status==="PAID"?"SUCCESS":payout.status}</span><strong>{money(payout.amount)}</strong></header><h2>{payout.riderName}</h2><a href={`tel:${payout.riderPhone}`}>{payout.riderPhone}</a><p>{payout.upiId}</p><small>{new Date(payout.createdAt+"Z").toLocaleString("en-IN")}</small>{payout.status==="PENDING"?<button disabled={busy} onClick={()=>approve(payout)}>Accept request</button>:payout.status==="APPROVED"?<button disabled={busy} onClick={()=>setPaying(payout)}>Pay</button>:<b>✓ Payment completed</b>}</article>)}{!payouts.length&&<Empty text="Withdrawal request aate hi yahan dikhegi"/>}</section>{paying&&<div className="payout-overlay" onClick={()=>setPaying(null)}><section className="payout-modal" onClick={event=>event.stopPropagation()}><button className="close" onClick={()=>setPaying(null)}>×</button><small>FIXED AMOUNT UPI PAYMENT</small><h2>{paying.riderName}</h2><strong>{money(paying.amount)}</strong><QRCodeSVG value={upiIntent} size={230} level="M" includeMargin/><p>{paying.upiId}</p><a href={upiIntent}>Open UPI app</a><button className="done" disabled={busy} onClick={complete}>{busy?"Saving…":"Done · Mark success"}</button><small>Payment karne ke baad hi Done dabayein.</small></section></div>}</>}

function Settings({data,send,busy}:{data:Data;send:(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void send("PATCH",{action:"settings",values:{upi_id:form.get("upi_id"),delivery_charge:form.get("delivery_charge"),support_number:form.get("support_number"),maintenance_mode:form.get("maintenance_mode")?"true":"false",order_accept_mode:form.get("order_accept_mode")}})}return <form className="settings-card" onSubmit={submit}><div><small>PAYMENT & OPERATIONS</small><h2>Global settings</h2><p>Checkout aur customer website par ye values live use hongi.</p></div><label>UPI ID<input name="upi_id" required defaultValue={data.settings.upi_id}/><small>Fixed amount UPI intent aur QR isi ID par banega.</small></label><label>Default delivery charge<input name="delivery_charge" type="number" required defaultValue={data.settings.delivery_charge||20}/></label><label>Support WhatsApp<input name="support_number" pattern="[0-9]{10}" required defaultValue={data.settings.support_number}/></label><label>Order acceptance<select name="order_accept_mode" defaultValue={data.settings.order_accept_mode||"MANUAL"}><option value="MANUAL">Manual accept</option><option value="AUTO">Auto confirm</option></select></label><label className="maintenance"><input name="maintenance_mode" type="checkbox" defaultChecked={data.settings.maintenance_mode==="true"}/><span><b>Maintenance mode</b><small>Customer ordering temporarily stop ho jayegi.</small></span></label><button disabled={busy}>Save settings</button></form>}

function Empty({text}:{text:string}){return <div className="panel-empty"><span>◇</span><b>{text}</b><small>Fresh setup ready hai.</small></div>}
